FROM openjdk:8-jdk-alpine
COPY target/node2-1.0-SNAPSHOT-jar-with-dependencies.jar node2-1.0-SNAPSHOT-jar-with-dependencies.jar
ENTRYPOINT ["java", "-jar", "node2-1.0-SNAPSHOT-jar-with-dependencies.jar"]
