FROM openjdk:8-jdk-alpine
COPY target/client-1.0-SNAPSHOT-jar-with-dependencies.jar client-1.0-SNAPSHOT-jar-with-dependencies.jar
ENTRYPOINT ["java", "-jar", "client-1.0-SNAPSHOT-jar-with-dependencies.jar"]
