FROM openjdk:8-jdk-alpine
COPY target/node1-1.0-SNAPSHOT-jar-with-dependencies.jar node1-1.0-SNAPSHOT-jar-with-dependencies.jar
ENTRYPOINT ["java", "-jar", "node1-1.0-SNAPSHOT-jar-with-dependencies.jar"]
