FROM openjdk:8-jdk-alpine
COPY target/node3-1.0-SNAPSHOT-jar-with-dependencies.jar node3-1.0-SNAPSHOT-jar-with-dependencies.jar
ENTRYPOINT ["java", "-jar", "node3-1.0-SNAPSHOT-jar-with-dependencies.jar"]
